name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "896c8564d8bf96758ab5781a59e1e2615df95acde9b156e48432e623bdf14ae5"

[versions]
fabric = "0.15.11"
minecraft = "1.18.2"
