name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be45339d339160f446be77080792a5d01b7703a3b4e202ea69672d16e7483091"

[versions]
fabric = "0.15.6"
minecraft = "1.18.2"
