name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29bdf39cb3ef8468d7d1bbe43560be73931b5c3aa73404a55a36b452ed1c2c5f"

[versions]
fabric = "0.14.19"
minecraft = "1.18.2"
