name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58b8e3ee6226ece4517ec5ac3b6bd546aac9d56d58f1d772c83095c4236f1910"

[versions]
fabric = "0.15.10"
minecraft = "1.18.2"
