name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59bb00c93aba60546f69cbc25e224d1058c2e0135bfa4b4141ee32ceb6a35df0"

[versions]
fabric = "0.15.6"
minecraft = "1.18.2"
