name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ded777ed89d6b0187e67bad0508a5ff36fa252b1aeb39d1e56e7b80db13cf36a"

[versions]
fabric = "0.14.24"
minecraft = "1.18.2"
