name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ddde7be9199af61be2870afc29433863ab64dfddb522f70d6f116de2f447474"

[versions]
fabric = "0.15.11"
minecraft = "1.18.2"
