name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5201054cf2c4867270d22bf142ab5949bc1e134e3287732573d7abc4b6eea44"

[versions]
fabric = "0.16.3"
minecraft = "1.18.2"
