name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1dc59ea4ff1514b4628d53fc2dc29930166252396db9204e4ed16882ad8202b3"

[versions]
fabric = "0.15.6"
minecraft = "1.18.2"
