name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c692d220e814622b6116cf06d1e2dd2a2247fcd8de9834b139ca75021e5dbc4c"

[versions]
fabric = "0.15.6"
minecraft = "1.18.2"
