name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a06e6e9aabf31ac7384f1cf71bc2176e25b45ced6d02835edc70ec649c9e0c81"

[versions]
fabric = "0.15.11"
minecraft = "1.18.2"
