name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5d7c35720f269981a219668fd13e2c9c0550517e5277d24f804d80062b39ecc"

[versions]
fabric = "0.16.3"
minecraft = "1.18.2"
