name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10368feaf080bc17300ba4db2593a8d3488250b5c16abceef033cafbbacd2f5d"

[versions]
fabric = "0.15.11"
minecraft = "1.18.2"
