name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9678abfbb27c17640a40e2e95640506f5773de295205a58eb78d40adf125ad4"

[versions]
fabric = "0.15.10"
minecraft = "1.18.2"
