name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6075af409c2a10d933f2f77638eba6edca088be3ac2ff486c53e5fc680a0394"

[versions]
fabric = "0.15.11"
minecraft = "1.18.2"
