name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bcdb170c32cd5aa14879879736d8545116fad41e2fbff66c26d7920f208fddfc"

[versions]
fabric = "0.15.11"
minecraft = "1.18.2"
