name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1459e66f13c2133c064d557e43f16e4e16d5cecfaa1506d630c45ecf083118af"

[versions]
fabric = "0.15.10"
minecraft = "1.18.2"
