name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddcea88c7070ed7f87a058e7a24c0d13f67b4aff2b5080fe53a031092d09243a"

[versions]
fabric = "0.15.11"
minecraft = "1.18.2"
