name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3a820d2ef2d3c70a28ce14c57cd31a6fec68f7312593d8f7e5221c5c449b4b1"

[versions]
fabric = "0.16.3"
minecraft = "1.18.2"
