name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52b4617e98cd71ffcbbd59ef3778037b3c4ed3e1dd50eb881082f04ad680480c"

[versions]
fabric = "0.15.11"
minecraft = "1.18.2"
