name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e01c6efef20158450f4809a5a26cecc5971877fdc3ffa1745b13bdf291ff70ed"

[versions]
fabric = "0.15.11"
minecraft = "1.18.2"
