name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fecf72b27d64b7f46d0117b4d0fe99fb272cf7728dab6340ef2e3d674bc78e37"

[versions]
fabric = "0.15.11"
minecraft = "1.18.2"
