name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86fd88628a7fcb2a8a353f0955717e6c9355458f39b1232c9895187cf0db6e1e"

[versions]
fabric = "0.15.11"
minecraft = "1.18.2"
