name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d57c3002ea4162752c16c61835b9e40f681b18584b7e570709f9328548216cbe"

[versions]
fabric = "0.15.11"
minecraft = "1.18.2"
