name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acf76c9496679663f1accfac9011b1f635700f62e9e3fabc0eb08d260000a316"

[versions]
fabric = "0.15.10"
minecraft = "1.18.2"
