name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea75f39c853c9102757aaf4753dbe2ffb0f83048c9479d496d64e68294ccbd01"

[versions]
fabric = "0.15.6"
minecraft = "1.18.2"
