name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ac64fa7288ef7bbecd06a3e5e35ca73de0700e00488762158c6f5cc0c84a2b5"

[versions]
fabric = "0.15.11"
minecraft = "1.18.2"
