name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98773e11db9888dedd39dc586597177d65b5af09be51181fcf98a7b236adf00f"

[versions]
fabric = "0.15.6"
minecraft = "1.18.2"
