name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ce35978c8d4793e1a4fc4c854fb635ab68111be2bd4a41c34c36d2dccb06d11"

[versions]
fabric = "0.15.10"
minecraft = "1.18.2"
