name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77db968644c0ebbd5171f494a53a01894eb15a51b46427b4788d6b2150ab8c8f"

[versions]
fabric = "0.16.3"
minecraft = "1.18.2"
