name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "134fd96e526cb4fa40a99508cafbcf0d2447a87bb864efce006aae9bc684db88"

[versions]
fabric = "0.15.11"
minecraft = "1.18.2"
