name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71d6501e4d9005f3f1043e57624e5fdf62d77ddcc05db944fdc02d5c4979c539"

[versions]
fabric = "0.15.11"
minecraft = "1.18.2"
