name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4c77962e0ebe6070f220fa28bea3ecf0e6de507c34f309ace805c19ef359ffe"

[versions]
fabric = "0.16.3"
minecraft = "1.18.2"
