name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d2c4e6858e63ace22564b05e6fec04933d232250f3cce257db67eb642fbd834"

[versions]
fabric = "0.15.10"
minecraft = "1.18.2"
